### PR TITLE
Add handling for persp renaming

### PR DESCRIPTION
**Pull request by samrjack**
## Commit message
Add handling for persp renaming

Keep state consistent when persp renames its perspectives.

## Background summary
I often rename perspectives when working with them and have noticed a lot of weird behavior with my zoom windows. I decided to debug it and am raising this PR to correct the behavior. I raised [this](https://github.com/emacsorphanage/zoom-window/issues/22) issue to track it as well.

## Solution summary
In order to solve this issue, I am creating a new function to hook into persp to be notified whenever a perspective changes names. This function updates `zoom-window--window-configuration` and ` zoom-window--put-alist` so they reflect the new name.

## Other notes
I used a `let... when...` structure instead of the `when-let` macro since `when-let` was introduced in emacs 25.1 and it seems the package is still trying to target emacs 24.3.

I also updated all the hook functions to use the `#'<function>` syntax since I've seen that as generally clean style. If you wish that to be reverted, I'm happy to do so.

### CODE REVIEW

**Review by jcs090218 — APPROVED** [review]
LGTM!

I don't use persp-mode so I would have to trust you on this! :)

**Comment by samrjack** [comment]
As long as the methodology of updating the `zoom-window` variables seems fine, I don't think there will be a problem. I had to do some investigation in the first place to find out about the persp behavior 😅.

**Comment by jcs090218** [comment]
I'm waiting for the GHA to work in case there are no general errors (installing, packaging, etc). I have requested to org owners in #24.

**Comment by jcs090218** [comment]
Thank you!

**Comment by samrjack** [comment]
Awesome!

**Pull request merged**
